---
title: "NMDS"
author: "Kelle"
date: "2024-11-4"
output: html_document
---


import data
```{r}
library(here)
library(tidyverse)
library(plotly)
library(vegan)
library(ggplot2)
library(ggplotify)
library(sjPlot)

setwd("/Users/kellefreel/Documents/HIMB/Projects/SAR11/Freel_manu_SAR11/data/NMDS_metagenomes_jan25/")
coverage.in <- read.csv(file = here("/Users/kellefreel/Documents/HIMB/Projects/SAR11/Freel_manu_SAR11/data/NMDS_metagenomes_jan25/Q2Q3.csv"))
detection.in <- read.csv(file = here("/Users/kellefreel/Documents/HIMB/Projects/SAR11/Freel_manu_SAR11/data/NMDS_metagenomes_jan25/DETECTION.csv"))
sar11.info.in <- read.table(file = here("/Users/kellefreel/Documents/HIMB/Projects/SAR11/Freel_manu_SAR11/data/NMDS_metagenomes_jan25/SAR11-INFO.txt"), header = T)

```

add metadata and transpose
```{r}
coverage <- coverage.in %>% filter(metagenome!="LEW_ERR771105_OSD14_1m")
detection <- detection.in %>% filter(metagenome!="LEW_ERR771105_OSD14_1m")
sar11.info <- sar11.info.in
```

transpose
```{r}
coverage_t <- coverage %>% pivot_longer(!metagenomes, names_to = "genome", values_to = "cov") %>% pivot_wider(names_from = metagenomes, values_from = cov) %>% full_join(.,sar11.info %>% select(c("genome", "type", "sublineage")), by = "genome") %>% relocate(genome, type, sublineage)

detection_t <- detection %>% pivot_longer(!metagenomes, names_to = "genome", values_to = "cov") %>% pivot_wider(names_from = metagenomes, values_from = cov) %>% full_join(.,sar11.info %>% select(c("genome", "type", "sublineage")), by = "genome") %>% relocate(genome, type, sublineage)
```

nmds
```{r}
#coverage
cov.nmds.matrix <- as.matrix(coverage_t[,4:ncol(coverage_t)])
cov.nmds.matrix_rm0 <- cov.nmds.matrix[, colSums(cov.nmds.matrix != 0) > 0]
cov.nmds <-  metaMDS(cov.nmds.matrix_rm0, distace = "bray")

#cov.nmds
#plot(cov.nmds)

cov.scores <-  as.data.frame(scores(cov.nmds)$sites)
cov.scores$genome <- coverage_t$genome 
cov.scores$type <- coverage_t$type
cov.scores$sublineage <- coverage_t$sublineage

ggplotly(ggplot(cov.scores, aes(x = NMDS1, y = NMDS2, label = genome)) + 
  geom_point(size = 3, aes(colour = sublineage)) + 
    geom_text(alpha=0))

#detection
det.nmds.matrix <- as.matrix(detection_t[,4:ncol(detection_t)])
det.nmds.matrix_rm0 <- det.nmds.matrix[, colSums(det.nmds.matrix != 0) > 0]
det.nmds <-  metaMDS(det.nmds.matrix_rm0, distace = "bray")

#det.nmds
#plot(det.nmds)

det.scores <-  as.data.frame(scores(det.nmds)$sites)
det.scores$genome <- detection_t$genome 
det.scores$type <- detection_t$type
det.scores$sublineage <- detection_t$sublineage

ggplotly(ggplot(det.scores, aes(x = NMDS1, y = NMDS2, label = genome)) + 
  geom_point(size = 3, aes(colour = sublineage)) + 
    geom_text(alpha=0))

ggplotly(ggplot(det.scores, aes(x = NMDS1, y = NMDS2, label = genome)) + 
  geom_point(size = 3, aes(colour = sublineage)) + 
    geom_text(alpha=0))


color_mapping <- c("Ia.3.V"  = "#5e4fa2", 
                  "Ia.3.VI"  = "#3288bd", 
                  "Ia.3.VII"  = "#66c2a5", 
                  "Ia.3.I"  = "#f5f5ba", 
                  "Ia.3.IV"  = "#c1e3bc", 
                  "Ia.4.N6"  = "#aefcce", 
                  "Ia.4.N5"  = "#9e0142", 
                  "Ia.4.N3"  = "#dadb84", 
                  "Ia.4.N4"  = "#72bab4", 
                  "Ia.4.N2"  = "#ed7b89", 
                  "Ia.4.N1"  = "#cc4968", 
                  "Ia.4.II"  = "#fdae61", 
                  "Ia.3.II"  = "#f59342", 
                  "Ia.3.III"  = "#d53e4f", 
                  "Ia.1.I"  = "#fdae61", 
                  "Ib.2.I"  = "#658ea8", 
                  "Ib.N7"  = "#336c8f", 
                  "Ib.1"  = "#8cc2b1", 
                  "Ib.1.III"  = "#afcf91", 
                  "Ib.N10"  = "#a9bdc9", 
                  "Ib.3"  = "#75beeb", 
                  "Ib.4.I"  = "#6dc290", 
                  "Ib.4.N8"  = "#74ab8b", 
                  "Ib.4.N9"  = "#aefcce", 
                  "Ib.N11"  = "#c3e0bf", 
                  "Ic"  = "#58508d", 
                  "II"  = "#bc5090", 
                  "III"  = "#ff6361", 
                  "IV"  = "#ffa600")

ggplotly(ggplot(det.scores, aes(x = NMDS1, y = NMDS2, label = genome)) + 
  geom_point(size = 3, aes(colour = sublineage)) + 
    scale_colour_manual(values = color_mapping) +
    geom_text(alpha=0))

test <- ggplotly(ggplot(det.scores, aes(x = NMDS1, y = NMDS2, label = genome)) + 
  geom_point(size = 4.5, aes(colour = sublineage, shape = type), alpha = 0.7) + 
    scale_colour_manual(values = color_mapping) +
    geom_text(alpha=0))

shape_mapping <- c("NA" = 16, "isolate" = 17, "SAG" = 18)

# Add scale_shape_manual to set specific shapes
plot <- plot + scale_shape_manual(values = shape_mapping)


    qplot(clarity, data=diamonds, fill=cut, geom="bar")
#save the plot in a variable image to be able to export to svg
    image=ggplotly(ggplot(det.scores, aes(x = NMDS1, y = NMDS2, label = genome)) + 
  geom_point(size = 4.5, aes(colour = sublineage, shape = type), alpha = 0.7) + 
    scale_colour_manual(values = color_mapping) +
    geom_text(alpha=0))
#This actually save the plot in a image
    ggsave(file="/Users/kellefreel/Documents/HIMB/Projects/SAR11/Freel_manu_SAR11/data/NMDS_metagenomes_jan25/images/nmds_v1.svg", plot=image, width=10, height=8)
    
    
ggplot(det.scores, aes(x = NMDS1, y = NMDS2, label = genome)) + 
  geom_point(size = 4.5, aes(colour = sublineage, shape = type), alpha = 0.7) + 
    scale_colour_manual(values = color_mapping) +
    geom_text(alpha=0)

ggsave("/Users/kellefreel/Documents/HIMB/Projects/SAR11/Freel_manu_SAR11/data/NMDS_metagenomes_jan25/images/nmds_v1.svg")

ggsave("/Users/kellefreel/Documents/HIMB/Projects/SAR11/Freel_manu_SAR11/data/NMDS_metagenomes_jan25/images/nmds_v1.svg", width = 50, height = 30, units = "cm")

ggsave("/Users/kellefreel/Documents/HIMB/Projects/SAR11/Freel_manu_SAR11/data/NMDS_metagenomes_jan25/images/nmds_v2.svg", width = 50, height = 50, units = "cm")


install.packages("htmlwidgets")
library(htmlwidgets)

ggplotly(ggplot(det.scores, aes(x = NMDS1, y = NMDS2, label = genome)) + 
  geom_point(size = 4.5, aes(colour = sublineage, shape = type), alpha = 0.7) + 
    scale_colour_manual(values = color_mapping) +
    geom_text(alpha=0))

ggsave("/Users/kellefreel/Documents/HIMB/Projects/SAR11/Freel_manu_SAR11/data/NMDS_metagenomes_jan25/images/nmds_v3.svg", width = 50, height = 30, units = "cm")


install.packages("htmlwidgets")
library(htmlwidgets)

ggplotly_to_save <- ggplotly(ggplot(det.scores, aes(x = NMDS1, y = NMDS2, label = genome)) + 
  geom_point(size = 4.5, aes(colour = sublineage, shape = type), alpha = 0.7) + 
    scale_colour_manual(values = color_mapping) +
    geom_text(alpha=0))

# save
saveWidget(widget = ggplotly_to_save,
           file = "/Users/kellefreel/Documents/HIMB/Projects/SAR11/Freel_manu_SAR11/data/NMDS_metagenomes_jan25/images/nmds_v3.html")
    
```


